services:

  semaphore:
    container_name: semaphore
    restart: unless-stopped
    image: semaphoreui/semaphore:latest
    env_file:
      - .semaphore.env
    environment:
      SEMAPHORE_DB_DIALECT: bolt
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.semaphore.rule=Host(`semaphore.${BASE_DOMAIN:-ozeliurs.com}`)"
      - "traefik.http.routers.semaphore.entrypoints=websecure"
      - "traefik.http.routers.semaphore.tls=true"
      - "traefik.http.routers.semaphore.tls.certresolver=cloudflare"
      - "traefik.http.services.semaphore.loadbalancer.server.port=3000"

networks:
  traefik:
    external: true